### ISSUE TITLE
System Requirements

### ISSUE THREAD

**Issue by davetcoleman** [dbader/photosorter#6]
Wow this looks like just what I need! But it doesn't say what platform it is targeted at - OSX or Linux? Any specific distros? Perhaps you can add this to the README...

Thanks for sharing!

**Comment by dbader** [comment]
I run it on Linux (Ubuntu 16.04) but it should work on OS X as well. It might even work on Windows, but I've never tried ;-)

**Comment by ardyflora** [comment]
Is this up for grab? I have windows laptop and I can try to work on it.  I think I can help here, and also it will be a great learning experience to go through all the code and try to understand it. 

Please let me know :)

**Comment by davetcoleman** [comment]
Closing this issue because I documented it
