### ISSUE TITLE
Suggest making sorter.py non-executable

### ISSUE THREAD

**Issue by dionsongus** [dbader/photosorter#8]
Dan:

Fascinating code. Not only is it an excellent py.test tutorial, it's something I can actually use at home, first such an example for me. 

I'd suggest making sorter.py non-executable though to make it a little more user friendly. There's no guarantee my python is in /user/bin/env, right?

**Comment by dbader** [comment]
Thanks @dionsongus, glad you found this code helpful.

Re: `env` in the shebang line: https://stackoverflow.com/questions/2429511/why-do-people-write-the-usr-bin-env-python-shebang-on-the-first-line-of-a-pyt
